name: Python Tests

on:
  push:
    branches: [main, nightly]
    paths:
      - "py/**"
      - ".github/workflows/py.yml"
  pull_request:
    branches: [main, nightly]
    paths:
      - "py/**"
      - ".github/workflows/py.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install
        working-directory: py

      - name: Install dependencies
        run: uv sync
        working-directory: py

      - name: Run linter
        run: uv run ruff check
        working-directory: py

      - name: Check formatting
        run: uv run ruff format --check
        working-directory: py

      - name: Run tests
        run: uv run pytest
        working-directory: py
